- name: Add Erlang Solutions repository
  apt:
    deb: https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb
- name: Install Erlang and Elixir
  apt:
    update_cache: yes
    pkg:
      - esl-erlang
      - elixir
- name: Add Nodesource GPG key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
- name: Add Nodesource debian repo
  apt_repository:
    repo: deb https://deb.nodesource.com/node_14.x buster main
- name: Install NodeJS via Nodesource repo
  apt:
    update_cache: yes
    pkg:
      - nodejs


